apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: billing-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: nyc-transit
  name: billing-service
  namespace: nyc-transit
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: billing-service
status:
  loadBalancer: {}
